### ISSUE TITLE
Fix normal vs. dev dependencies

### ISSUE THREAD

**Issue by joeyfigaro** [hayanisaid/rnal#9]
Installing rnal currently causes a haste module naming collision because two copies of `react-native`  exist in node_modules—one for whatever project installed rnal, and rnal's copy at `node_modules/rnal/node_modules/react-native`

Fastest way to address this is to move `react-native` to `devDependencies`

**Comment by joeyfigaro** [comment]
@hayanisaid I can take a look at a PR for this this weekend if you haven't gotten to it

**Comment by hayanisaid** [comment]
@joeyfigaro  Please do it thanks.

**Comment by joeyfigaro** [comment]
@hayanisaid Got the changes ready, just need to wrap up testing everything out. Should have it pushed up for ya by midweek.

**Comment by joeyfigaro** [comment]
@hayanisaid PR up for ya

**Comment by hayanisaid** [comment]
Hi @joeyfigaro Thanks for the PR I'm reviewing it now 😃

**Comment by joeyfigaro** [comment]
Taken care of in #15
